language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - rbx-head
before_install:
  - sudo apt-get install libraptor1
  - sudo ln -s /usr/lib/libraptor.so.1 /usr/lib/libraptor.so
